import { useEffect, useRef, useState } from 'react';
import { Board } from './Board';
import type { Tool } from './Board';
import { jsonPost, request, useRoom } from './client';
import { makeId, newPiece, rawPiece, sceneEdit } from './model';
import type { Snapshot } from './model';
import { PieceInspector, SceneSettings, TurnPanel, duplicatePieces } from './Inspector';
import './tabletop.css';
const roles={gm:'主持人',player:'玩家',spectator:'观战者'};
const tools:[Tool,string,string][]=[['select','↖','选择'],['pan','✥','平移'],['token','◉','棋子'],['note','T','文字'],['measure','⌁','测距'],['circle','◯','圆形'],['rect','□','矩形'],['cone','◔','扇形'],['line','╱','线形'],['polygon','⬡','多边形'],['ping','◎','指示']];
async function copy(value:string){if(!navigator.clipboard)throw new Error('浏览器不允许自动复制，请选中文本复制');await navigator.clipboard.writeText(value);}
function joinData(){const params=new URLSearchParams(location.hash.slice(1));const invite=params.get('invite')||'';if(invite)history.replaceState(history.state,'',location.pathname+location.search);return invite;}
export default function Tabletop(){
  const room=new URLSearchParams(location.search).get('room')||'';
  return room&&/^[a-zA-Z0-9_-]{1,64}$/.test(room)?<Room key={room} room={room}/>:<Lobby/>;
}
function Lobby(){
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[enabled,setEnabled]=useState<boolean|null>(null),[roomUrl,setRoomUrl]=useState('');
  useEffect(()=>{request<{creation_enabled:boolean}>('/health').then(r=>setEnabled(r.creation_enabled)).catch(()=>setError('战术桌服务暂不可用，请检查后端是否已经更新。'));},[]);
  return <main className="tt-app tt-lobby"><header className="tt-lobby-head"><a href="/">∞ 宏观界域</a><span>TACTICAL TABLE / 自由战术桌</span></header>
    <div className="tt-lobby-layout"><section className="tt-lobby-story"><div className="tt-eyebrow">诸界之间 · 同桌而行</div><h1>把战场摆清楚。<br/><em>让规则保持自由。</em></h1><p>地图、棋子、距离与范围。<br/>不绑定人物卡，不替主持人裁定战斗。</p><div className="tt-mini-board" aria-hidden="true"><span className="tt-mini-zone"/><i>界</i><i>旅</i><i>影</i></div><div className="tt-lobby-notes"><span>01 / 真实联机</span><span>02 / 自由尺度</span><span>03 / 服务器保存</span></div></section>
    <section className="tt-lobby-card"><small>OPEN A NEW REALM</small><h2>创建战术房间</h2><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const data=new FormData(e.currentTarget);try{const result=await jsonPost<{room:string}>('/rooms',Object.fromEntries(data));location.assign('/tabletop.html?room='+result.room);}catch(error){setError(error instanceof Error?error.message:'创建失败');setBusy(false);}}}>
      <label>房间名称<input name="name" maxLength={80} required placeholder="例如：诸界远征 · 城市遭遇"/></label><label>主持人昵称<input name="nick" maxLength={40} required placeholder="你的称呼"/></label><label>建房口令<input name="key" type="password" autoComplete="off" maxLength={256} required placeholder="由网站维护者分发，不是后台密码"/></label>
      {enabled===false&&<p className="tt-warning">此服务器尚未启用建房。维护者需配置 TABLETOP_CREATE_KEY；玩家加入现有房间不需要此口令。</p>}
      <button className="tt-primary" disabled={busy||enabled===false}>{busy?'正在创建…':'创建房间 ↗'}</button>
    </form><p className="tt-help">主持人身份保存在此浏览器，30天有效。请保留此浏览器数据并定期导出备份；不要把主持人的浏览器交给玩家。</p>
    <div className="tt-divider"/><h3>已有邀请？</h3><form onSubmit={e=>{e.preventDefault();try{const url=new URL(roomUrl,location.origin);if(url.origin!==location.origin||(url.pathname!=='/tabletop.html'||!/^[a-zA-Z0-9_-]{1,64}$/.test(url.searchParams.get('room')||'')))throw new Error('请粘贴本站的完整房间邀请链接');location.assign(url.pathname+url.search+url.hash);}catch(error){setError(error instanceof Error?error.message:'链接无效');}}}><label>房间邀请链接<input type="text" value={roomUrl} onChange={e=>setRoomUrl(e.target.value)} placeholder="粘贴主持人发给你的链接" required/></label><button>进入房间</button></form>
    {error&&<p role="alert" className="tt-warning">{error}</p>}</section></div></main>;
}
function Room({room}:{room:string}){
  const api=useRoom(room),{state,status,busy,error,setError,act,upload}=api;
  const [invite]=useState(joinData),[panel,setPanel]=useState<'object'|'scene'|'members'|'turn'|'backup'|null>(null);
  const [tool,setTool]=useState<Tool>('select'),[selected,setSelected]=useState<string[]>([]),[notice,setNotice]=useState(''),[working,setWorking]=useState(false);
  const [joinError,setJoinError]=useState(''),[joinBusy,setJoinBusy]=useState(false),[inviteOut,setInviteOut]=useState('');
  const [calibration,setCalibration]=useState<{length:number;scene:string;version:number}|null>(null);
  const inviteDialog=useRef<HTMLDialogElement>(null),calibrationDialog=useRef<HTMLDialogElement>(null),inviteButton=useRef<HTMLButtonElement>(null);
  const gm=state?.role==='gm',disabled=status!=='online'||busy||working, readOnly=state?.role==='spectator';
  const chosen=state?selected.map(id=>state.scene.pieces[id]).filter(Boolean):[];
  useEffect(()=>{if(state)setSelected(ids=>ids.filter(id=>!!state.scene.pieces[id]));},[state?.scene.id,state?.revision]);
  useEffect(()=>{if(!state){setSelected([]);setPanel(null);setInviteOut('');inviteDialog.current?.close();}},[!!state]);
  useEffect(()=>{if(calibration&&!calibrationDialog.current?.open)calibrationDialog.current?.showModal();},[calibration]);
  const changeTool=(value:Tool)=>{setTool(value);if(value!=='select')setPanel(null);};
  const dismissInvite=()=>{inviteDialog.current?.close();setInviteOut('');inviteButton.current?.focus();};
  if(status==='unauthorized')return <main className="tt-app tt-join"><a href="/tabletop.html">∞ 界域战术桌</a><section className="tt-lobby-card"><small>JOIN THE TABLE</small><h1>加入房间</h1><p>填写昵称即可。权限由邀请类型与主持人分配决定。</p><form onSubmit={async e=>{e.preventDefault();setJoinBusy(true);setJoinError('');try{await jsonPost('/'+room+'/join',Object.fromEntries(new FormData(e.currentTarget)));api.reconnect();}catch(error){setJoinError(error instanceof Error?error.message:'加入失败');}finally{setJoinBusy(false);}}}><label>你的昵称<input name="nick" required maxLength={40} placeholder="昵称不是身份凭证"/></label><label>邀请凭证<input name="invite" type="password" defaultValue={invite} required maxLength={256} placeholder="从邀请链接自动读取"/></label><button className="tt-primary" disabled={joinBusy}>{joinBusy?'正在加入…':'加入战术桌'}</button></form><p className="tt-help">未收到邀请或身份已被撤销时，请向主持人索取新链接。</p>{joinError&&<p role="alert" className="tt-warning">{joinError}</p>}</section></main>;
  if(!state)return <main className="tt-app tt-join"><section className="tt-lobby-card"><h1>正在连接战术桌…</h1><p role="status">{status==='offline'?'连接中断，正在重试。':'正在验证房间身份并读取已保存的战场。'}</p><button onClick={api.reconnect}>重新连接</button><a href="/tabletop.html">返回入口</a></section></main>;
  const addToken=async()=>{const piece=newPiece('token',{x:8+Object.keys(state.scene.pieces).length%8*3,y:8},state.me);if(await act({kind:'pieces',edits:[{id:piece.id,expected:0,value:rawPiece(piece)}]})){setSelected([piece.id]);setPanel('object');}};
  return <main className="tt-app tt-desk" data-revision={state.revision}>
    <header className="tt-topbar"><a className="tt-logo" href="/tabletop.html" title="战术桌入口">∞</a><strong title={state.name}>{state.name}</strong>
      <select aria-label="切换战术场景" value={state.scene.id} disabled={!gm||disabled} onChange={e=>void act({kind:'scene.switch',scene:e.target.value})}>{state.scenes.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>
      <span className={`tt-connection ${status}`} role="status" data-connection={status}>{status==='online'?(busy||working?'保存中…':'已连接'):'断线 · 暂停编辑'}</span>
      <div className="tt-top-actions"><button aria-pressed={panel==='members'} onClick={()=>setPanel(panel==='members'?null:'members')}>成员 <span>{state.members.filter(m=>m.online).length}</span></button>{gm&&<button ref={inviteButton} disabled={disabled} onClick={()=>inviteDialog.current?.showModal()}>邀请</button>}<button aria-pressed={panel==='scene'} onClick={()=>setPanel(panel==='scene'?null:'scene')}>场景</button><button aria-pressed={panel==='backup'} onClick={()=>setPanel(panel==='backup'?null:'backup')}>更多</button></div>
    </header>
    <div className="tt-map-shell"><nav className="tt-tools" aria-label="战术工具">{tools.map(([value,icon,name])=><button key={value} title={name} aria-label={name+'工具'} aria-pressed={tool===value} disabled={disabled&&!['select','pan','measure'].includes(value)||readOnly&&!['select','pan','measure'].includes(value)||value==='ping'&&!gm} onClick={()=>changeTool(value)}><b aria-hidden="true">{icon}</b><span>{name}</span></button>)}<div className="tt-tool-divider"/><button title="撤销我的上次对象编辑；不会覆盖后续操作" aria-label="撤销操作" disabled={disabled||readOnly||!state.canUndo} onClick={()=>void act({kind:'undo'})}><b>↶</b><span>撤销</span></button><button aria-label="行动记录" aria-pressed={panel==='turn'} onClick={()=>setPanel(panel==='turn'?null:'turn')}><b>≡</b><span>行动</span></button></nav>
      <Board state={state} disabled={disabled||readOnly} tool={tool} setTool={setTool} selected={selected} onSelect={setSelected} act={act} onInspect={()=>setPanel('object')} onCalibrate={length=>setCalibration({length,scene:state.scene.id,version:state.scene.v})}/>
      <div className="tt-room-identity">{roles[state.role]} · {state.members.find(m=>m.id===state.me)?.name}<span>v{state.revision}</span></div>
      {chosen.length>0&&<div className="tt-selection-actions"><span>{chosen.length===1?chosen[0].name:`已选 ${chosen.length} 项`}</span><button onClick={()=>setPanel(panel==='object'?null:'object')}>属性</button><button disabled={disabled||readOnly||!chosen.every(p=>p.editable)||chosen.length>100} onClick={()=>void act(duplicatePieces(chosen,state.me,!!gm))}>复制</button><button className="tt-danger" disabled={disabled||readOnly||!chosen.every(p=>p.editable)||chosen.length>100} onClick={async()=>{if(!confirm(`删除选中的 ${chosen.length} 个对象？跟随范围需先解除绑定。`))return;if(await act({kind:'pieces',edits:chosen.map(p=>({id:p.id,expected:p.v,value:null}))}))setSelected([]);}}>删除</button></div>}
      {Object.keys(state.scene.pieces).length===0&&panel===null&&<div className="tt-board-empty"><small>你的战场，由你定义</small><h2>{state.scene.background?'底图已就位':'从一张空白战场开始'}</h2><p>摆棋子、画领域、量距离。<br/>所有规则仍由主持人裁定。</p>{!readOnly&&<button className="tt-primary" disabled={disabled} onClick={()=>void addToken()}>放置第一个棋子</button>}{gm&&<button onClick={()=>setPanel('scene')}>上传底图</button>}</div>}
      {panel&&<aside className="tt-sidepanel" aria-label="战术桌侧面板">
        <div className="tt-panel-tabs">{([['object','对象'],['scene','场景'],['members','成员'],['turn','行动'],['backup','更多']] as const).map(([value,label])=><button key={value} aria-pressed={panel===value} onClick={()=>setPanel(value)}>{label}</button>)}<button aria-label="关闭战术侧栏" onClick={()=>setPanel(null)}>×</button></div>
        {panel==='object'&&(chosen[0]?<PieceInspector key={chosen[0].id} state={state} piece={chosen[0]} disabled={disabled} act={act} upload={upload} onClose={()=>setPanel(null)}/>:<div className="tt-properties"><h2>战场对象</h2><p className="tt-help">点选地图或下方名称，打开属性。玩家只能编辑授权对象。</p>{!readOnly&&<button disabled={disabled} onClick={()=>void addToken()}>＋ 新棋子</button>}</div>)}
        {panel==='object'&&<div className="tt-object-list" aria-label="可见对象列表">{Object.values(state.scene.pieces).map(p=><button key={p.id} aria-pressed={selected.includes(p.id)} onClick={()=>setSelected([p.id])}><span>{p.kind==='token'?'◉':'◇'} {p.name}</span><small>{p.visibility==='gm'?'仅 KP':p.visibility==='selected'?'指定可见':''}</small></button>)}</div>}
        {panel==='scene'&&<SceneSettings state={state} disabled={disabled} act={act} upload={upload} onCalibrate={()=>changeTool('calibrate')}/>}
        {panel==='members'&&<div className="tt-properties"><h2>房间成员</h2><p className="tt-help">同名不等于同一身份。分配控制权请在棋子属性里操作。</p>{state.members.map(m=><div className="tt-member-row" key={m.id}><span className={m.online?'online-dot':'offline-dot'}/><div><b>{m.name}{m.id===state.me?'（我）':''}</b><small>{roles[m.role]} · {m.id.slice(-4)}</small></div>{gm&&m.role!=='gm'&&<button disabled={disabled} onClick={()=>{if(confirm(`撤销 ${m.name} 的房间身份？其连接将断开。`))void act({kind:'member',data:{id:m.id}});}}>撤销</button>}</div>)}</div>}
        {panel==='turn'&&<TurnPanel state={state} disabled={disabled} act={act}/>}
        {panel==='backup'&&<div className="tt-properties"><h2>保存与资料</h2><p className="tt-help">已确认操作在服务器保存。不同玩家的镜头独立；断线时暂停共享修改，重连后以服务器为准。</p><button onClick={api.reconnect}>重新连接房间</button><a className="tt-text-link" href="/" target="_blank" rel="noopener noreferrer">打开序列库查规则 ↗</a>
          {gm&&<><h3>房间备份</h3><p className="tt-warning">备份包含主持人私密备注和隐藏对象，请勿发给玩家。身份和邀请凭证不包含在备份内。</p><button disabled={disabled} onClick={async()=>{setWorking(true);try{const value=await request(`/${room}/export`);const url=URL.createObjectURL(new Blob([JSON.stringify(value)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='界域战术桌-备份.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}catch(error){setError(error instanceof Error?error.message:'备份失败');}finally{setWorking(false);}}}>导出含图片备份</button>
          <label className="tt-upload">导入为新场景<input disabled={disabled} type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>120*1024*1024){setError('备份超过120MB');return;}if(!confirm('导入为新场景，不覆盖现有场景。所有导入对象先设为仅主持人可见，需要重新分配可见性和控制权。'))return;setWorking(true);try{const result=await request<Snapshot>(`/${room}/import`,{method:'POST',headers:{'Content-Type':'application/json','X-Operation-Id':makeId()},body:f});api.apply(result);setNotice('导入完成，可在顶部选择新场景。请先检查可见性再向玩家展示。');}catch(error){setError(error instanceof Error?error.message:'导入失败');}finally{setWorking(false);e.target.value='';}}}/></label></>}
          <h3>桌面操作</h3><p className="tt-help">空格＋拖动：平移；滚轮 / 双指：缩放。Shift＋点击：多选；空白拖动：框选。回车完成线形 / 多边形，Esc 取消绘制。双击对象查看属性。</p><p className="tt-help">技术边界：每房间20场景、每场景500对象、24个成员身份、80MB素材；非游戏规则上限。</p>
        </div>}
      </aside>}
    </div>
    {(error||notice)&&<div className={'tt-toast'+(error?' is-error':'')} role={error?'alert':'status'}><span>{error||notice}</span><button aria-label="关闭提示" onClick={()=>{setError('');setNotice('');}}>×</button></div>}
    <dialog className="tt-dialog" ref={inviteDialog} aria-labelledby="tt-invite-title" onCancel={()=>setInviteOut('')}><div className="tt-panel-title"><h2 id="tt-invite-title">邀请同桌</h2><button onClick={dismissInvite} aria-label="关闭邀请">×</button></div><p>邀请不包含主持人权限。生成新链接会使该类型的旧邀请失效，但不踢出已经加入的成员。</p><div className="tt-form-pair">{(['player','spectator'] as const).map(role=><button key={role} disabled={disabled} onClick={async()=>{try{const result=await jsonPost<{invite:string}>(`/${room}/invite/${role}`,{});setInviteOut(`${location.origin}/tabletop.html?room=${room}#invite=${encodeURIComponent(result.invite)}`);}catch(error){setError(error instanceof Error?error.message:'邀请生成失败');}}}>生成{roles[role]}邀请</button>)}</div>{inviteOut&&<><label>邀请链接<textarea readOnly value={inviteOut} rows={3} onFocus={e=>e.target.select()}/></label><button className="tt-primary" onClick={()=>copy(inviteOut).then(()=>setNotice('邀请链接已复制')).catch(error=>setError(error.message))}>复制邀请链接</button></>}</dialog>
    <dialog className="tt-dialog" ref={calibrationDialog} aria-labelledby="tt-calibrate-title" onClose={()=>setCalibration(null)}><h2 id="tt-calibrate-title">校准底图比例尺</h2><p>所选两点的当前距离：{calibration?.length.toFixed(3)} 米。只调整底图尺寸，不移动已有棋子或范围。</p><form onSubmit={async e=>{e.preventDefault();if(!calibration)return;if(calibration.scene!==state.scene.id||calibration.version!==state.scene.v){setError('场景已改变，请重新选择校准点');calibrationDialog.current?.close();return;}const actual=Number(new FormData(e.currentTarget).get('actual')),ratio=actual/calibration.length;if(Number.isFinite(ratio)&&ratio>0&&await act(sceneEdit(state.scene,{map_width:state.scene.map_width*ratio,map_height:state.scene.map_height*ratio})))calibrationDialog.current?.close();}}><label>实际距离（米）<input name="actual" type="number" min="0.001" max="10000000" step="any" required autoFocus/></label><button className="tt-primary" disabled={disabled||!calibration||calibration.length<.00001}>应用比例尺</button><button type="button" onClick={()=>calibrationDialog.current?.close()}>取消</button></form></dialog>
  </main>;
}
